version: '3.9'
services:
  twic:
    build:
      context: .
      args:
        GIT_SHA: ${GIT_SHA:-dev}
        BUILD_DATE: ${BUILD_DATE:-dev}
    image: twic:dev
    environment:
      ENABLE_METRICS: "1"
      FASTAPI_ENABLE_DOCS: "1"
      REQUEST_RATE_LIMIT: "200"
      RATE_LIMIT_WINDOW_S: "60"
      DEFAULT_LANG: "es"
      REDIS_URL: ${REDIS_URL:-}
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./models:/app/models
      - ./scripts:/app/scripts
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--reload"]
    ports:
      - "8000:8000"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server","--save","","--appendonly","no"]
