version: '3.9'
services:
  twic:
    image: ghcr.io/ORG_PLACEHOLDER/twic:0.2.0
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--workers","2"]
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    read_only: true
    tmpfs:
      - /tmp
    user: "1000:1000"
    environment:
      ENABLE_METRICS: "1"
      REQUEST_RATE_LIMIT: "120"
      RATE_LIMIT_WINDOW_S: "60"
      MAX_QUERY_CHARS: "512"
      DEFAULT_LANG: "es"
    labels:
      org.opencontainers.image.source: "https://github.com/ORG_PLACEHOLDER/twic"
      org.opencontainers.image.version: "0.2.0"
