name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'
            cache: 'pip'
      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint (ruff)
        run: ruff check .
      - name: Type check (mypy)
        run: mypy app scripts
      - name: Tests (pytest)
        run: pytest -q --maxfail=1 --disable-warnings
      - name: Show disk usage (debug)
        if: always()
        run: df -h .